name: github pages deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout git-lfs objects
      run: git lfs checkout

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    
    - name: Run npm install
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
